name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  vm-test:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - name: install packages
        run: nix profile add --inputs-from . nixpkgs#niks3
      - name: Get niks3 path
        id: niks3
        run: |
          path=$(which niks3)
          echo "store-path=$path" >> "$GITHUB_OUTPUT"
      - uses: Mic92/niks3-action@12d3e320b2a99b7938f9634bd337cd9fec104609 # v1.1.0
        with:
          server-url: https://niks3.s.ihavenojob.work
          niks3-bin: ${{ steps.niks3.outputs.store-path }}
      - name: Run OP-TEE VM test
        run: nix flake check --accept-flake-config
